<template>
  <!-- Generated by IcoMoon.io -->
  <div class="icon icon-about header__link-icon">
    <svg v-for="(icon, index) in amount" :key="index" :width="iconWidth" :height="iconHeight" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
      <title>About</title>
      <path :fill="iconColor" d="M12 1c-6.1 0-11 4.9-11 11s4.9 11 11 11 11-4.9 11-11-4.9-11-11-11zM12 21c-5 0-9-4-9-9s4-9 9-9c5 0 9 4 9 9s-4 9-9 9z"></path>
      <path :fill="iconColor" d="M13.2 6.2c-2.1-0.7-4.4 0.4-5.1 2.4-0.1 0.6 0.1 1.2 0.7 1.3 0.5 0.2 1.1-0.1 1.3-0.6 0.4-1 1.5-1.6 2.6-1.2 0.8 0.3 1.3 1 1.3 1.9 0 1-1.7 1.8-2.3 2.1-0.5 0.2-0.8 0.7-0.6 1.3 0.1 0.4 0.5 0.7 0.9 0.7 0.1 0 0.2 0 0.3-0.1 0.4-0.1 3.7-1.3 3.7-3.9-0.1-1.8-1.2-3.3-2.8-3.9z"></path>
      <path :fill="iconColor" d="M11.3 16.3c-0.2 0.2-0.3 0.4-0.3 0.7s0.1 0.5 0.3 0.7c0.2 0.2 0.4 0.3 0.7 0.3s0.5-0.1 0.7-0.3c0.2-0.2 0.3-0.5 0.3-0.7s-0.1-0.5-0.3-0.7c-0.4-0.4-1-0.4-1.4 0z"></path>
    </svg>
  </div>
</template>

<script>
export default {
  props: [
    'iconColor',
    'iconWidth',
    'iconHeight',
    'amount'
  ]
}
</script>
